import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Greeting from "../components/Greeting";
import NavBar from "../components/NavBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Greeting />
      <About />
    </>
  );
};

export default Home;
