import axios from "axios";
import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Greeting from "../components/Greeting";
import NavBar from "../components/NavBar";
import Projects from "../components/Projects";

const Home: NextPage = ({
  projectsData,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-dark-100">
        <NavBar />
        <Greeting />
        <About />
        <Projects projects={projectsData} />
        <Contact />
        <Footer />
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const projects = await axios.get(`${process.env.API_URL}/api/projects`);
  return {
    props: {
      projectsData: projects.data,
    },
  };
};

export default Home;
